In [17]:
clean_df = pd.read_csv("../data/processed/jobs_master.csv")
clean_df.head()

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780,"linear algebra, quantum algorithms",No,Large,2025-07-22
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481,"climate data analysis, energy modeling",Yes,Large,2025-09-26
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081,"linear algebra, qiskit",No,Medium,2025-12-31
3,4,Sustainability Analyst,Green Tech,Singapore,113822,"climate data analysis, energy modeling",No,Large,2025-05-29
4,5,Smart Contract Engineer,Blockchain,London,92575,"rust, solidity",Yes,Small,2025-03-30

In [16]:
df.to_csv("../data/processed/jobs_master.csv", index=False)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           10000 non-null  int64
 1   job_title        10000 non-null  str
 2   industry         10000 non-null  str
 3   location         10000 non-null  str
 4   salary_usd       10000 non-null  int64
 5   skills_required  10000 non-null  str
 6   remote_option    10000 non-null  str
 7   company_size     10000 non-null  str
 8   posting_date     10000 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(2), str(6)
memory usage: 703.3 KB

In [13]:
df["posting_date"] = pd.to_datetime(df["posting_date"])

In [12]:
df["job_title"] = df["job_title"].str.title()
df["industry"] = df["industry"].str.title()
df["location"] = df["location"].str.title()
df["skills_required"] = df["skills_required"].str.lower()
df["remote_option"] = df["remote_option"].str.title()
df["company_size"] = df["company_size"].str.title()

In [11]:
text_columns = [
    "job_title",
    "industry",
    "location",
    "skills_required",
    "remote_option",
    "company_size"
]

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [10]:
df = df.drop_duplicates()

In [9]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

job_id             0
job_title          0
industry           0
location           0
salary_usd         0
skills_required    0
remote_option      0
company_size       0
posting_date       0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           10000 non-null  int64
 1   job_title        10000 non-null  str
 2   industry         10000 non-null  str
 3   location         10000 non-null  str
 4   salary_usd       10000 non-null  int64
 5   skills_required  10000 non-null  str
 6   remote_option    10000 non-null  str
 7   company_size     10000 non-null  str
 8   posting_date     10000 non-null  str
dtypes: int64(2), str(7)
memory usage: 703.3 KB

In [6]:
df.columns

Index(['job_id', 'job_title', 'industry', 'location', 'salary_usd',
       'skills_required', 'remote_option', 'company_size', 'posting_date'],
      dtype='str')

In [5]:
df.head()

,job_id,job_title,industry,location,salary_usd,skills_required,remote_option,company_size,posting_date
0,1,Quantum Researcher,Quantum Computing,Singapore,175780,"Linear Algebra, Quantum Algorithms",No,Large,2025-07-22
1,2,Renewable Energy Engineer,Green Tech,Singapore,137481,"Climate Data Analysis, Energy Modeling",Yes,Large,2025-09-26
2,3,Quantum Researcher,Quantum Computing,Tokyo,182081,"Linear Algebra, Qiskit",No,Medium,2025-12-31
3,4,Sustainability Analyst,Green Tech,Singapore,113822,"Climate Data Analysis, Energy Modeling",No,Large,2025-05-29
4,5,Smart Contract Engineer,Blockchain,London,92575,"Rust, Solidity",Yes,Small,2025-03-30

In [4]:
df = pd.read_csv("../data/raw/future_jobs_dataset.csv")

In [3]:
import pandas as pd